// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtDCqSuksC0DJY80wpOWn-QznPAiJaLNc',
    appId: '1:959513450126:android:2ef20f62d22800e7821bdf',
    messagingSenderId: '959513450126',
    projectId: 'iqrosoft-7c2f1',
    storageBucket: 'iqrosoft-7c2f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF0Gc5Ag_hP4dzJGfpYPfxKNzwY0e_GOQ',
    appId: '1:959513450126:ios:07c5bfe22e8506d8821bdf',
    messagingSenderId: '959513450126',
    projectId: 'iqrosoft-7c2f1',
    storageBucket: 'iqrosoft-7c2f1.appspot.com',
    iosBundleId: 'com.example.iqroCleanFromScratch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF0Gc5Ag_hP4dzJGfpYPfxKNzwY0e_GOQ',
    appId: '1:959513450126:ios:837ff4d63d224eba821bdf',
    messagingSenderId: '959513450126',
    projectId: 'iqrosoft-7c2f1',
    storageBucket: 'iqrosoft-7c2f1.appspot.com',
    iosBundleId: 'com.example.iqroCleanFromScratch.RunnerTests',
  );
}
